language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR= .

install:
  - pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - qio platform install https://github.com/OS-Q/P11/releases/latest/download/package.zip

script:
  - qio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
